# Generated by Django 5.2.10 on 2026-01-13 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('post', 'Post'), ('like', 'Like'), ('comment', 'Comment'), ('notifications', 'Others')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
